# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from turtlebot3_msgs/SensorState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class SensorState(genpy.Message):
  _md5sum = "427f77f85da38bc1aa3f65ffb673c94c"
  _type = "turtlebot3_msgs/SensorState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """########################################
# CONSTANTS
########################################
# Bumper states (states are combined, when multiple bumpers are pressed)
uint8 BUMPER_RIGHT  = 1
uint8 BUMPER_CENTER = 2
uint8 BUMPER_LEFT   = 4

# Cliff sensor states (states are combined, when multiple cliff sensors are triggered)
uint8 CLIFF_RIGHT  = 1
uint8 CLIFF_CENTER = 2
uint8 CLIFF_LEFT   = 4

# Button states (only one button can be triggered at a time)
uint8 BUTTON0 = 1
uint8 BUTTON1 = 2
uint8 BUTTON2 = 4

# Motor errors
uint8 ERROR_LEFT_MOTOR  = 1
uint8 ERROR_RIGHT_MOTOR = 2

########################################
# Messages
########################################
time stamp
uint8  bumper
uint8  cliff
uint8  button
int32  left_encoder    # (-2,147,483,648 ~ 2,147,483,647)
int32  right_encoder   # (-2,147,483,648 ~ 2,147,483,647)
float32  battery
"""
  # Pseudo-constants
  BUMPER_RIGHT = 1
  BUMPER_CENTER = 2
  BUMPER_LEFT = 4
  CLIFF_RIGHT = 1
  CLIFF_CENTER = 2
  CLIFF_LEFT = 4
  BUTTON0 = 1
  BUTTON1 = 2
  BUTTON2 = 4
  ERROR_LEFT_MOTOR = 1
  ERROR_RIGHT_MOTOR = 2

  __slots__ = ['stamp','bumper','cliff','button','left_encoder','right_encoder','battery']
  _slot_types = ['time','uint8','uint8','uint8','int32','int32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,bumper,cliff,button,left_encoder,right_encoder,battery

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SensorState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.bumper is None:
        self.bumper = 0
      if self.cliff is None:
        self.cliff = 0
      if self.button is None:
        self.button = 0
      if self.left_encoder is None:
        self.left_encoder = 0
      if self.right_encoder is None:
        self.right_encoder = 0
      if self.battery is None:
        self.battery = 0.
    else:
      self.stamp = genpy.Time()
      self.bumper = 0
      self.cliff = 0
      self.button = 0
      self.left_encoder = 0
      self.right_encoder = 0
      self.battery = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I3B2if().pack(_x.stamp.secs, _x.stamp.nsecs, _x.bumper, _x.cliff, _x.button, _x.left_encoder, _x.right_encoder, _x.battery))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 23
      (_x.stamp.secs, _x.stamp.nsecs, _x.bumper, _x.cliff, _x.button, _x.left_encoder, _x.right_encoder, _x.battery,) = _get_struct_2I3B2if().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I3B2if().pack(_x.stamp.secs, _x.stamp.nsecs, _x.bumper, _x.cliff, _x.button, _x.left_encoder, _x.right_encoder, _x.battery))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 23
      (_x.stamp.secs, _x.stamp.nsecs, _x.bumper, _x.cliff, _x.button, _x.left_encoder, _x.right_encoder, _x.battery,) = _get_struct_2I3B2if().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I3B2if = None
def _get_struct_2I3B2if():
    global _struct_2I3B2if
    if _struct_2I3B2if is None:
        _struct_2I3B2if = struct.Struct("<2I3B2if")
    return _struct_2I3B2if
