// Generated by gencpp from file turtlebot3_msgs/SetFollowState.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_MSGS_MESSAGE_SETFOLLOWSTATE_H
#define TURTLEBOT3_MSGS_MESSAGE_SETFOLLOWSTATE_H

#include <ros/service_traits.h>


#include <turtlebot3_msgs/SetFollowStateRequest.h>
#include <turtlebot3_msgs/SetFollowStateResponse.h>


namespace turtlebot3_msgs
{

struct SetFollowState
{

typedef SetFollowStateRequest Request;
typedef SetFollowStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFollowState
} // namespace turtlebot3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot3_msgs::SetFollowState > {
  static const char* value()
  {
    return "6095eaec0ed61c547340fdc2200c8372";
  }

  static const char* value(const ::turtlebot3_msgs::SetFollowState&) { return value(); }
};

template<>
struct DataType< ::turtlebot3_msgs::SetFollowState > {
  static const char* value()
  {
    return "turtlebot3_msgs/SetFollowState";
  }

  static const char* value(const ::turtlebot3_msgs::SetFollowState&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot3_msgs::SetFollowStateRequest> should match 
// service_traits::MD5Sum< ::turtlebot3_msgs::SetFollowState > 
template<>
struct MD5Sum< ::turtlebot3_msgs::SetFollowStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot3_msgs::SetFollowState >::value();
  }
  static const char* value(const ::turtlebot3_msgs::SetFollowStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot3_msgs::SetFollowStateRequest> should match 
// service_traits::DataType< ::turtlebot3_msgs::SetFollowState > 
template<>
struct DataType< ::turtlebot3_msgs::SetFollowStateRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot3_msgs::SetFollowState >::value();
  }
  static const char* value(const ::turtlebot3_msgs::SetFollowStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot3_msgs::SetFollowStateResponse> should match 
// service_traits::MD5Sum< ::turtlebot3_msgs::SetFollowState > 
template<>
struct MD5Sum< ::turtlebot3_msgs::SetFollowStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot3_msgs::SetFollowState >::value();
  }
  static const char* value(const ::turtlebot3_msgs::SetFollowStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot3_msgs::SetFollowStateResponse> should match 
// service_traits::DataType< ::turtlebot3_msgs::SetFollowState > 
template<>
struct DataType< ::turtlebot3_msgs::SetFollowStateResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot3_msgs::SetFollowState >::value();
  }
  static const char* value(const ::turtlebot3_msgs::SetFollowStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT3_MSGS_MESSAGE_SETFOLLOWSTATE_H
